#!/bin/sh

set -eox

GH_ACCOUNT=jwfh
GH_REPO=freebsd-init

WRKDIR="$(mktemp -d)"

PORTS='	
	devel/gmake 
	devel/p5-subversion 
	devel/git 
	security/sudo 
	devel/llvm80 
	devel/meson 
	print/ghostscript9-agpl-base 
	print/tex-dvipsk
	editors/vim
'
DISABLE_VULNERABILITIES='
	print/ghostscript9-agpl-base 
'

fetch_repo() {
	echo "Fetching files from VCS to ${WRKDIR}"
	cd "${WRKDIR}" && \
		fetch -o- https://api.github.com/repos/${GH_ACCOUNT}/${GH_REPO}/releases/latest \
			| sed -E -e 's@^.*"tarball_url":"@@' -e 's@".*$@@' \
			| xargs fetch -o- \
			| tar xvf - --strip 1
}

install_port_options() {
	echo "Installing port options"
}

install_if_not_exists() {
	echo "Building $1"
	if echo ${DISABLE_VULNERABILITIES} | grep -q $1; then
		echo make -C ${PORTSDIR}/$1 DISABLE_VULNERABILITIES=yes install
	else
		echo make -C ${PORTSDIR}/$1 install
	fi
}

install_ports() {
	for port in ${PORTS}
	do
		install_if_not_exists ${port}
	done
}

main() {
	fetch_repo
	install_port_options
	install_ports
}

main

rm -rf "${WRKDIR}"
